# Generated by Django 5.2.1 on 2025-05-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
