# Generated by Django 5.2.1 on 2025-05-23 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_app', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='signup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
